id: P000691
initial_creation_type: ocr
source_metadata:
  id: bdr:W2PD19386
  title: ངེས་ཤེས་རིན་པོ་ཆེའི་སྒྲོན་མེད་དང་མཁས་འཇུག་གི་སྡོམ་བྱང་།
  author: ''
  volumes:
    3dc49f15632d418ab9bf745c355d9fb9:
      image_group_id: I2PD19912
      title: ''
      volume_number: 1
      total_pages: 100
