id: P000691
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-16 16:37:20.031899
source_metadata:
  id: bdr:W2PD19386
  title: ངེས་ཤེས་རིན་པོ་ཆེའི་སྒྲོན་མེད་དང་མཁས་འཇུག་གི་སྡོམ་བྱང་།
  author: ''
  volumes:
    3dc49f15632d418ab9bf745c355d9fb9:
      image_group_id: I2PD19912
      title: ''
      volume_number: 1
      total_pages: 100
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
